version: 0.2
env:
    shell: bash

phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - pip install --upgrade pip
    build:
        commands:
            - echo deploy started on `date`
            - aws cloudformation package --template-file template.yml --s3-bucket $ARTIFACT_BUCKET_NAME --output-template-file outputtemplate.yml --debug

artifacts:
    files:
        - template.yml
        - outputtemplate.yml